const $=s=>document.querySelector(s),original=$('#original'),overlay=$('#overlay'),file=$('#file-input'),slider=$('#threshold'),run=$('#run');
const exampleNames=['01_polyp.jpg','02_sessile_polyp.jpg','03_colon_polyp.jpg','04_sessile_polyp.jpg','05_stalked_polyp.jpg'];
let worker,imageData,imageName='',inputSize,ready=false,busy=false,requestId=0,loadId=0,lastResult,mask,sliderTimer;
const buttons=[$('#export-overlay'),$('#export-mask'),$('#export-json')];
function status(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error);}
function busyState(value){busy=value;run.disabled=value||!imageData;file.disabled=value;slider.disabled=value;document.querySelectorAll('.sample').forEach(b=>b.disabled=value);$('#run-label').textContent=value?'Working…':'Run analysis';$('#run-icon').className=value?'spinner':'';$('#run-icon').textContent=value?'':'↗';}
function clearResult(){ready=false;lastResult=null;mask=null;buttons.forEach(b=>b.disabled=true);overlay.getContext('2d').clearRect(0,0,overlay.width,overlay.height);$('#overlay-placeholder').hidden=false;$('#count').textContent='No prediction yet';$('#result-note').textContent='Run analysis to inspect candidate regions.';$('#timing').textContent='—';$('#regions').innerHTML='<tr class="empty-row"><td colspan="5">Candidate regions will appear after analysis.</td></tr>';}
function resultIsCurrent(){return ready&&lastResult?.id===requestId&&lastResult.threshold===Number(slider.value);}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function basename(){return imageName.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80)||'endoscope';}
function beginSelection(){const own=++loadId;requestId++;clearTimeout(sliderTimer);clearResult();imageData=null;original.getContext('2d').clearRect(0,0,original.width,original.height);$('#original-placeholder').hidden=false;$('#file-info').textContent='Opening image…';run.disabled=true;status('Opening image…');return own;}
async function loadImage(blob,name,sampleIndex=-1,own=beginSelection()){if(busy||own!==loadId)return;if(blob.size>20*1024*1024){$('#file-info').textContent='No image selected';status('Please choose an image smaller than 20 MB.',true);return;}const url=URL.createObjectURL(blob);try{const im=new Image();im.src=url;await im.decode();if(own!==loadId)return;if(im.naturalWidth*im.naturalHeight>20000000)throw Error('Image exceeds 20 megapixels. Please resize it first.');const scale=Math.min(1,Math.sqrt(4000000/(im.naturalWidth*im.naturalHeight)),4096/Math.max(im.naturalWidth,im.naturalHeight));const w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale));inputSize={width:im.naturalWidth,height:im.naturalHeight};original.width=w;original.height=h;overlay.width=w;overlay.height=h;const ctx=original.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);ctx.drawImage(im,0,0,w,h);imageData=ctx.getImageData(0,0,w,h);imageName=name;$('#original-placeholder').hidden=true;$('#file-info').textContent=name+' · '+w+' × '+h+(scale<1?' (resized locally)':'');document.querySelectorAll('.sample').forEach((b,i)=>b.classList.toggle('active',i===sampleIndex));run.disabled=false;status('Image ready. Select Run analysis.');}catch(e){if(own!==loadId)return;imageData=null;run.disabled=true;$('#file-info').textContent='No image selected';$('#original-placeholder').hidden=false;original.getContext('2d').clearRect(0,0,original.width,original.height);status(e.message.includes('megapixels')?e.message:'Could not open this image. Try a JPG, PNG, or WebP file.',true);}finally{URL.revokeObjectURL(url);}}
exampleNames.forEach((name,i)=>{const b=document.createElement('button');b.className='sample';b.title='Load sample '+(i+1);b.setAttribute('aria-label','Load sample '+(i+1));const im=document.createElement('img');im.src='/assets/examples/'+name;im.alt='Public endoscopic polyp sample '+(i+1);b.append(im);b.addEventListener('click',async()=>{if(busy)return;const own=beginSelection();try{const r=await fetch(im.src);if(!r.ok)throw Error();await loadImage(await r.blob(),name,i,own);}catch{if(own!==loadId)return;$('#file-info').textContent='No image selected';status('Sample could not be loaded. Try uploading an image.',true);}});$('#samples').append(b);});
file.addEventListener('change',()=>{if(file.files[0])loadImage(file.files[0],file.files[0].name);});
const drop=$('#drop-zone');for(const name of ['dragover','dragenter'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('dragover');});for(const name of ['dragleave','drop'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('dragover');});drop.addEventListener('drop',e=>{if(!busy&&e.dataTransfer.files[0])loadImage(e.dataTransfer.files[0],e.dataTransfer.files[0].name);});
function getWorker(){if(worker)return worker;worker=new Worker('/try/inference-worker.js');worker.onmessage=({data})=>{if(data.id!==requestId)return;if(data.type==='status'){status(data.message);return;}if(data.type==='error'){busyState(false);clearResult();status('Analysis failed: '+data.message+' You can retry.',true);return;}if(data.type==='result'){ready=true;busyState(false);lastResult=data;mask=new Uint8Array(data.mask);drawResult();status('Analysis complete. Adjust the threshold to explore.');}};worker.onerror=()=>{busyState(false);clearTimeout(sliderTimer);clearResult();status('The browser engine could not start. Please reload or try a current Chrome, Edge, Firefox, or Safari browser.',true);worker.terminate();worker=null;};return worker;}
run.addEventListener('click',()=>{if(!imageData||busy)return;clearTimeout(sliderTimer);const pixels=imageData.data.slice();clearResult();busyState(true);status('Starting local analysis…');const id=++requestId;try{getWorker().postMessage({id,type:'analyze',width:original.width,height:original.height,pixels:pixels.buffer,threshold:Number(slider.value)},[pixels.buffer]);}catch(e){busyState(false);clearResult();status('This browser could not start the inference engine: '+e.message,true);}});
slider.addEventListener('input',()=>{$('#threshold-value').textContent=Number(slider.value).toFixed(2);if(!ready||busy)return;buttons.forEach(b=>b.disabled=true);clearTimeout(sliderTimer);const id=++requestId,threshold=Number(slider.value);status('Updating the mask…');$('#result-note').textContent='Updating the selected threshold; exports are temporarily unavailable.';sliderTimer=setTimeout(()=>{if(id!==requestId||!imageData||!ready)return;try{getWorker().postMessage({id,type:'threshold',threshold});}catch(e){clearResult();status('The mask could not be updated. Run analysis again.',true);}},100);});
function drawResult(){const ctx=overlay.getContext('2d'),pixels=new Uint8ClampedArray(imageData.data);for(let i=0;i<mask.length;i++)if(mask[i]){pixels[i*4]=Math.floor(pixels[i*4]*.6+28*.4);pixels[i*4+1]=Math.floor(pixels[i*4+1]*.6+221*.4);pixels[i*4+2]=Math.floor(pixels[i*4+2]*.6+176*.4);}ctx.putImageData(new ImageData(pixels,original.width,original.height),0,0);const font=Math.max(10,Math.round(Math.min(original.width,original.height)/38));ctx.font='600 '+font+'px sans-serif';ctx.lineWidth=Math.max(2,Math.round(Math.min(original.width,original.height)/200));lastResult.regions.forEach((r,i)=>{const [x,y,x2,y2]=r.bbox_xyxy;ctx.strokeStyle='#21edbf';ctx.strokeRect(x,y,x2-x-1,y2-y-1);const label='#'+(i+1)+' CANDIDATE',tw=ctx.measureText(label).width+8,ty=Math.max(0,y-font-8);ctx.fillStyle='#073d35';ctx.fillRect(x,ty,Math.min(tw,overlay.width-x),font+7);ctx.fillStyle='white';ctx.fillText(label,x+4,ty+font+1);});$('#overlay-placeholder').hidden=true;const n=lastResult.regions.length;$('#count').textContent=n+' candidate region'+(n===1?'':'s');$('#timing').textContent=Math.round(lastResult.metrics.model_inference_ms)+' ms · model only';const body=$('#regions');body.replaceChildren();for(const [i,r]of lastResult.regions.entries()){const tr=document.createElement('tr');[i+1,'Polyp candidate',r.mean_model_score.toFixed(3),'['+r.bbox_xyxy.join(', ')+']',r.area_pixels.toLocaleString()].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});body.append(tr);}if(!n)body.innerHTML='<tr class="empty-row"><td colspan="5">No candidate regions at this threshold. This does not rule out a polyp.</td></tr>';$('#result-note').textContent='Result threshold: '+lastResult.threshold.toFixed(2)+'. Each box encloses a connected region of at least 16 pixels.';buttons.forEach(b=>b.disabled=false);$('#threshold-value').textContent=lastResult.threshold.toFixed(2);slider.value=lastResult.threshold;}
$('#export-overlay').addEventListener('click',()=>{if(!resultIsCurrent())return;const name=basename()+'_overlay.png';overlay.toBlob(blob=>blob&&download(blob,name));});
$('#export-mask').addEventListener('click',()=>{if(!resultIsCurrent())return;const name=basename()+'_mask.png';const c=document.createElement('canvas');c.width=original.width;c.height=original.height;const ctx=c.getContext('2d'),d=ctx.createImageData(c.width,c.height);for(let i=0;i<mask.length;i++){const v=mask[i]?255:0;d.data[i*4]=v;d.data[i*4+1]=v;d.data[i*4+2]=v;d.data[i*4+3]=255;}ctx.putImageData(d,0,0);c.toBlob(blob=>blob&&download(blob,name));});
$('#export-json').addEventListener('click',()=>{if(!resultIsCurrent())return;const r={project:'EndoScope AI',edition:'browser',research_only:true,supported_class:'polyp',source_filename:imageName,original_image_width:inputSize.width,original_image_height:inputSize.height,image_width:original.width,image_height:original.height,coordinates_refer_to:'working_image',threshold:lastResult.threshold,min_component_area_pixels:16,model_sha256:lastResult.metadata.checkpoint_sha256,onnx_sha256:lastResult.metadata.onnx_sha256,...lastResult.metrics,regions:lastResult.regions,notice:'Research prototype; scores are uncalibrated activations, not disease probabilities. No candidate does not establish a normal examination.'};download(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}),basename()+'_result.json');});

// Start with the same public sample used in the recorded walkthrough.
document.querySelector('.sample')?.click();
