importScripts('/assets/vendor/ort.wasm.min.js');
let sessionPromise,probability,width,height,metrics={},metadata;
const root=new URL('/',self.location.href);
ort.env.wasm.numThreads=1;
ort.env.wasm.proxy=false;
ort.env.wasm.wasmPaths=new URL('assets/vendor/',root).href;
const processing=import('./processing.mjs');
function session(){if(!sessionPromise){sessionPromise=Promise.all([ort.InferenceSession.create(new URL('assets/polyp.onnx',root).href,{executionProviders:['wasm'],graphOptimizationLevel:'all'}),fetch(new URL('assets/model-info.json',root)).then(r=>{if(!r.ok)throw Error('Model details could not be loaded.');return r.json();})]).then(([s,m])=>{metadata=m;return s;}).catch(e=>{sessionPromise=null;throw e;});}return sessionPromise;}
self.onmessage=async({data})=>{const {id,type,threshold}=data;try{const p=await processing;if(type==='analyze'){postMessage({type:'status',id,message:sessionPromise?'Analyzing image on your device…':'Loading the model and engine. First run may take a moment…'});const s=await session();postMessage({type:'status',id,message:'Analyzing image on your device…'});const start=performance.now();width=data.width;height=data.height;const input=p.prepareImage(new Uint8ClampedArray(data.pixels),width,height);const t0=performance.now();const tensor=new ort.Tensor('float32',input.tensor,[1,3,160,160]);const output=await s.run({image:tensor});const ms=performance.now()-t0;const grid=output.probability.data;if(!grid.every(Number.isFinite))throw Error('Model returned invalid scores. Please retry.');probability=p.restoreProbability(grid,width,height,input.box);metrics={model_inference_ms:ms,processing_ms_before_regions:performance.now()-start};tensor.dispose();output.probability.dispose();}if(!probability)throw Error('Run analysis before adjusting the result.');const started=performance.now();const result=p.findRegions(probability,width,height,threshold);postMessage({id,type:'result',mask:result.mask.buffer,regions:result.regions,threshold,width,height,metadata,metrics:{...metrics,region_processing_ms:performance.now()-started}},[result.mask.buffer]);}catch(error){postMessage({id,type:'error',message:error.message||String(error)});}};
