const video=document.querySelector('#demo-video');
const caption=document.querySelector('#caption');
const list=document.querySelector('#chapters');
let language='en',steps=[],active=-1;
const format=t=>'0:'+String(Math.floor(t)).padStart(2,'0');
function setTracks(){for(const track of video.textTracks)track.mode='disabled';if(document.fullscreenElement===video&&video.textTracks.length)video.textTracks[language==='en'?0:1].mode='showing';}
function update(){if(!steps.length)return;let i=steps.findIndex(s=>video.currentTime>=s.start&&video.currentTime<s.end);if(i<0)i=steps.length-1;if(i!==active){active=i;list.querySelectorAll('button').forEach((b,j)=>{b.classList.toggle('active',i===j);if(i===j)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});}caption.textContent=steps[i]['caption_'+language];document.querySelector('#caption-index').textContent=String(i+1).padStart(2,'0')+' / 08';caption.lang=language==='zh'?'zh-CN':'en';}
function render(){list.replaceChildren();steps.forEach((s,i)=>{const b=document.createElement('button');b.className='chapter';const n=document.createElement('span');n.className='chapter-no';n.textContent=String(i+1).padStart(2,'0');const title=document.createElement('span');title.textContent=s[language];const time=document.createElement('time');time.textContent=format(s.start);b.append(n,title,time);b.addEventListener('click',()=>{video.currentTime=s.start;video.play().catch(()=>{});update();});list.append(b);});active=-1;update();}
for(const lang of ['en','zh'])document.querySelector('#lang-'+lang).addEventListener('click',()=>{language=lang;for(const l of ['en','zh'])document.querySelector('#lang-'+l).setAttribute('aria-pressed',String(l===lang));document.querySelector('#download-subtitles').href='/assets/captions/'+lang+'.srt';setTracks();render();});
video.addEventListener('timeupdate',update);video.addEventListener('seeked',update);video.addEventListener('loadedmetadata',setTracks);document.addEventListener('fullscreenchange',setTracks);video.addEventListener('webkitbeginfullscreen',()=>{if(video.textTracks.length)video.textTracks[language==='en'?0:1].mode='showing';});video.addEventListener('webkitendfullscreen',setTracks);
document.querySelector('#replay').addEventListener('click',()=>{video.currentTime=0;video.play().catch(()=>{});});
fetch('/assets/chapters.json').then(r=>{if(!r.ok)throw Error('Chapters unavailable');return r.json();}).then(x=>{steps=x;render();}).catch(()=>{caption.textContent='Use the video controls to play the recording. Subtitle files are available below.';});
